### ISSUE TITLE
[Question] When is the next release scheduled?

### ISSUE THREAD

**Issue by Rob3rtS** [TimelordUK/node-sqlserver-v8#348]
Hi,

We are trying to build msnodesqlv8 v4.2.1 locally from source for NodeJs v22.11.0 (on Windows, using VS 2022, during `npm install`), but it fails with:
```
...\node-sqlserver-v8\src\OdbcOperation.cpp(120,58): error C2668: 'Nan::New': ambiguous call to overload
ed function [...\node-sqlserver-v8\build\sqlserverv8.vcxproj]
```

On master, it got already fixed by commit [ffc6b63a1bc5ccddd6ec25c40208f8d6724e835d](https://github.com/TimelordUK/node-sqlserver-v8/commit/ffc6b63a1bc5ccddd6ec25c40208f8d6724e835d).
A new release containing this fix would help us to overcome the issue above, as we cannot use precompiled binaries in our network situation.

Thanks,
Robert

**Comment by TimelordUK** [comment]
will try and release in next 48 hrs

**Comment by TimelordUK** [comment]
Can you try latest

**Comment by Rob3rtS** [comment]
Thanks - it works fine with v4.4.0.
